### ISSUE TITLE
How can i train my own data?

### ISSUE THREAD

**Issue by talatccan** [rikenshah/predict-next-word#2]
Hi,

I tested it and it worked very well. First of all thank you for it.

Now what i want to do is that, i want to train my own data for another language. Which steps should i follow?

**Comment by rikenshah** [comment]
Line 4-25 in `bigramConditionalProbability` deals with making a dictionary from corpus. Now, one way would be to have your data in the same format as that of the [corpus](http://www.ngrams.info/download_coca.asp). Or, you can modify code in these lines to suit your data.
